### ISSUE TITLE
Takeover VimTutorial

### ISSUE THREAD

**Issue by wsdjeg** [zvim/VimTutorial#1]

**Comment by DaSea** [comment]
1, 提供工程功能;
2, 工程内跳转;
3,工程内搜索;
4,工程任务列表;
关于工程功能,我觉得可以采用exvim的

**Comment by wsdjeg** [comment]
1.目前我主要写的是Java 利用catags跳转的
2.另外一个插件辅助https://github.com/tpope/vim-projectionist
3.ctrlp 以及CtrlSF提供工程内搜索,配合多光标编辑插件,实现工程内批量修改
4.任务列表目前还没有好的插件
